### ISSUE TITLE
Agent disconnect

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#112]
All of the agents were disconnected and didn't reconnect after agent-manager.

Once connected to ,manager, agents should not exit on disconnection. It should keep on trying to connect to the backend.

### Log
![Image](https://github.com/user-attachments/assets/08ffc3ad-dcce-48f6-9719-b4481e1758c6)

### Todo:
- [x] When starting agent, try only up to max-attempts to connect to the manager.
- [x] Once agent is connected, when it gets disconnected from manager, then attempt reconnection forever ..

**Comment by Sital999** [comment]
Done
