### ISSUE TITLE
Fix Agent Display card

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#114]
Fix Issues in agent display card.

![Image](https://github.com/user-attachments/assets/9c640415-a763-4138-869e-4ce0d0452919)

Acceptance Criteria
- [x] `null` is not shown in agent card
- [x] Total functions is always 0.
- [x] make a icon and show total Transaction for the agent

**Comment by Sital999** [comment]
This ticket has been completed as mentioned above.

**Comment by mesudip** [comment]
This is deployed
