### ISSUE TITLE
Internal transactions are unstable

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#115]
It has been seen multiple times that internal transactions are tried multiple times, or the actual transaction is tried multiple time. 

![Image](https://github.com/user-attachments/assets/25836718-d676-447f-8c52-3b2856798f6d)

#### Acceptance Criteria
- [x] Internal transactions and followup transaction should not be repeated multiple times.

**Comment by Sital999** [comment]
It has been resolved
