### ISSUE TITLE
Show Agent Id or name in logs

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#119]
In Global logs page, show agentId and name and on clicking on it, user should be navigate to the agent's page.

### Acceptance Criteria
- [x] Agent id and name is displayed on the beginning of log with a icon.
- [x] User is routed to Agent detail page on clicking on agent icon. 
- [x] Use idinticon from agent's id.

**Link** https://github.com/stewartlord/identicon.js

**Comment by Sital999** [comment]
This is done and deployed

**Comment by mesudip** [comment]
This is deployed
