### ISSUE TITLE
Agent scenario tests

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#129]
### Pre-Requiresities

Update pytest with automated test that is capable of creating agents and executing a runner.

### Basic Scenarios
- When agent has cron trigger, the function is executed on that cron.
- When agent has event trigger, the function is executed when a transaction matching the condition is submitted on-chain

### Agent Scenarios
- When Agent received ada, refund it.
- Agent can vote on Proposals

**Comment by mesudip** [comment]
This ticket is extension of https://github.com/cardanoapi/autonomous-agents/issues/133

**Comment by mesudip** [comment]
> When Agent received ada, refund it.
Test is implemented
> Agent can vote on Proposals
This is pending

**Comment by JosephRana11** [comment]
The listed test scenarios have been completed. Allure test report has also been integrated and the previous gh branch has been reset.

Allure Test Report Link - [https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report](https://cardanoapi.github.io/autonomous-agents/test_backend_allure_report/2/)

Architecture doc New Link - [https://cardanoapi.github.io/autonomous-agents/archietecture_docusaurus/](https://cardanoapi.github.io/autonomous-agents/archietecture_docusaurus/)
