### ISSUE TITLE
Refactor Transaction Hold logic

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#149]
Update existing transaction hold  and tx-confirmation logic for new executor interface.

ToDos:
- [x] Add new builtin 'waitTxConfirmation'
- [x] Update wallet's buildAndSubmit to run only one instance of build and submit at a time.

**Comment by mesudip** [comment]
This is implemented in a feature branch

**Comment by spannercode** [comment]
@Sital999 Is this already merged to main?

**Comment by spannercode** [comment]
Merging to dev is fine. Lets close it for now.
