### ISSUE TITLE
Automatically create anchor data hash

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#179]
**When** I trigger a agent function manually,
**and** I have a url
**then** anchor-data-hash should be automatically calculated.

### Todo 
- [x] Backend : Add api to fetch/validate metadata (proxy to metadata.drep.id)
- [x] Frontend: Automatically add the calculated data hash in the ancho-data-hash field (handle onChange event)

**Comment by Sital999** [comment]
Done
