### ISSUE TITLE
Update Agent overview page

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#180]
As per decision in 
- https://github.com/cardanoapi/autonomous-agents/issues/178

Update agent overview page.

Following details should be present
- What is current balance 
- Which pool is the address delegated to
- which drep is the current address delegated to
- is this stake address registered as drep too? then what is the voting power for it, and  how many delegators do i have.
- What is currently snapshotted voting power (drep)
- Runner Status : (Last seen time of runner)

### Acceptance Criteria:
- [x] I can know whether the agent is drep is not from overview page.
- [x] I can know whether stake address is registered.
- [x] I can know which pool the address is delegated to.
- [x] I can know which drep the address is delegated to.
- [x] I can know voting power from overview page.

**Comment by Sital999** [comment]
For now except above two criteria remaining criteria are met as there is no api available in govtool for above two points.
