### ISSUE TITLE
Support Anchor Metadata

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#181]
**When** governance action is created or drep is registered, or vote is performed
**Then** if anchor information is missing, agent automatically creates a suitable metadata, registers it and sets the url/hash in the transaction.

Todo:
- [x] Add rpc to save metadata (should return hash and url)
- [x] Review formats for vote,drep registration and gov-actions and make function to create dummy ones with sensible data.
- [x] Update agent functions

**Comment by Sital999** [comment]
Done
