### ISSUE TITLE
Support for DRep and Governance metadata

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/autonomous-agents#209]
Lets create proper and compliant metadata for DRep and Governance Actions so that it is rendered well on our platform as well as on other platforms.

CIP 0119
CIP 0100

Notes:
- lets use proper language tag
- For DRep, lets use the additionals field that can be used to promote the platform (as links)

**Comment by Sital999** [comment]
The following changes have been made:
- Language has been added in proposal-metadata
- Links have been added in `Drep registration metadata`
- Also data has been properly formatted as required
