### ISSUE TITLE
Data from DB Sync

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/autonomous-agents#210]
Lets rely more on DB Sync than GovTool backend

For Governance metadata including DRep metadata

**Comment by Sital999** [comment]
On adding `language` in context of metadata data was updated on DB Sync but it took few minutes. 
With this it `dbsync_service` will return metadata for only newly created `drep` and `proposals`. So to support the existing `drep` and `proposals`,  `Drep metadata` service will also be integrated.
