### ISSUE TITLE
Encode DRep ID for normal display

### ISSUE THREAD

**Issue by spannercode** [cardanoapi/autonomous-agents#216]
Cardano users are more familiar with seeing encoded DRep ID encoded ad `drep1...` instead of hex representation. So, I suggest to show encoded DRep ID wherever relevant.

Here are some known places:
- DRep Directory
- Agent overview page

**Comment by Sital999** [comment]
It has been updated in frontend

**Comment by spannercode** [comment]
@Sital999 I assume it is not deployed yet.

**Comment by Sital999** [comment]
I have created a PR for it. It js under review.

**Comment by spannercode** [comment]
The feature/fix is deployed and accepted
