### ISSUE TITLE
Support retired dreps.

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#248]
in case of retired dreps, metadata should be taken from their 2nd'last registration transaction, and not the retired transaction.

To clarify, 
Dbsync has both registartion and de-registration in same table called `drep-registration`
**In case of retired dreps**, the metadata should be obtained not from the last drep-registartion transaction but the transaction before it where drep had updated/registered themselves.

#### Additionally,
add a field `isScript` to drep. the data is obtained from drep_hash table

### TODO
- [x] Add isScript field
- [x] Include metadata of retired dreps.

**Comment by Sital999** [comment]
It has been updated. But test cannot be performed since `cardano_node` was not connected so for this ticket , confirmation is remaining.
