### ISSUE TITLE
Handle voting on event based

### ISSUE THREAD

**Issue by Sital999** [cardanoapi/autonomous-agents#76]
### Goal
The goal of this ticket is to make an event-based trigger.
- [x] Event-Based-Trigger for the `Vote` function

### Description
Currently, the event-based trigger is kept only for the `Vote` Function. After it has been activated for the agent, it gets triggered for every `on_chain_transaction` if the body of the transaction consists of `ProposalProcedures`. 

Since the event-based trigger is only available for the `Vote` function it can be added to other functions as well in another ticket.

**Comment by mesudip** [comment]
Event based trigger is done and deployed to https://agents.cardnaoapi.io
