### ISSUE TITLE
Support Tx Submission Hold

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#81]
**When** an agent has a new behavior trigger,
**And** a transaction from previous trigger is still pending,
**Then** agent trigger should wait for previous transaction to be completed.

This is dependent on this issue: https://github.com/sireto/cardano-autonomous-agent/issues/85

**Comment by Sital999** [comment]
### Acceptance Criteria
- If an action is triggered then at first it checks whether existing timeout exists or not
    - If it exists then this trigger is added to the queue
    - Else it is triggered
- The next action on the queue is only triggered if:
    - the previous action `submitted txHash` matches with the hash of tx present in the block
    - Or if a timeout of 80 seconds is completed.

It has been completed and deployed
