### ISSUE TITLE
Support connecting to CAA with wallet.

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#83]
Support logging in with a wallet.
When connecting with wallet, 

- [x] - User should be asked to sign login message.
- [x] - User's stake will be used as their identifier.

When registering for the first time,
 

- [x] - a new agent is created with empty behavior for them.

When connected,

- [x]  - User can see myAgents tab. This should navigate to the user's agent.

When viewing user's agent tab,

- [x] - User can see the agent detail page for his agent.

- [x] - User can make modification to the behavior of this agent.

**Comment by JosephRana11** [comment]
Listed tasks along with Super Admin feature/authentication are completed. Currently working on test cases for authentication and updating prior  test cases to align with the updated APIs.

**Comment by mesudip** [comment]
This is done and deployed to staging
