### ISSUE TITLE
Organization of Functions

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#84]
In manual trigger, group the functions according to the purpose or type.

Eg. 

Registration
 - drep
 - stakeAddress
Proposal
 - info action
 - constitution
 ...
Delegation
 - by drep id
 - abstain
 - no-confidence

**Comment by Sital999** [comment]
### Description

Grouping of similar functions has been done both in the backend and frontend. Grouping is shown below:
- DRep
  - RegisterDRep
  - DeRegisterDrep
- Stake
  - RegisterStake
  - DeRegisterStake
- Delegation
  - Abstain
  - NoConfidence
  - StakeDelegation
- Vote
  - voteOnProposal
- Proposal
  - InfoAction 
  - New Constitution
- Others
  - Transfer ADA

Along with this
- New function `DeRegister Stake` is added
- Grouping of parameters for the functions consisting of parameters
- Validation of grouped parameters in frontend
