### ISSUE TITLE
Support Auto registration

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/autonomous-agents#93]
Example cases:

1. Voting
**When** agent performs a vote transaction
**And** transaction fails because it is not registered as drep
**Then** Agent should register as drep and retry the transaction

2. Delegation
**When** agent performs delegation
**And** transaction fails because stake address is not registered
**Then** Agent should create a  transaction with reg-deleg certificate.

**Comment by Sital999** [comment]
Above example cases has been handled and deployed in dev

**Comment by mesudip** [comment]
This is working
